# long description of module package
longDescription = """
gcc version 5.3.0

Usage Notes:
------------

Libraries Used:
---------------

Packages Used:
--------------

Optional Packages:
------------------
none

Testing:
--------
$ module load gcc_libs-5.3.0

--
Website: http://www.gcc.gnu.org/
 Source: http://mirrors.concertpass.com/gcc/releases/gcc-5.3.0/
   Test: See 'Testing' section above.
--
Build_Date: bioteam_2016_2_26 (http://wwww.bioteam.net)
"""

# short description of module package
shortDescription = """
This module contains the GNU compiler collection libraries
Version: 5.3.0 
"""

# load other modules required by this module
loadModules = [
"mpc/gcc/65/1.0.3", 
"gmp/gcc/65/6.1.0", 
"mpfr/gcc/64/3.1.3"
]

# prepend the given values for each of the listed environmental variables.
[prependEnv]
LD_LIBRARY_PATH = "/software/apps/gcc_libs/gcc/64/5.3.0/lib64"
LIBRARY_PATH = "/software/apps/gcc_libs/gcc/64/5.3.0/lib64"

# set the given environmental variables to the provided values
# NOTE: If the environmental variable exists it will be overwritten
[setEnv]
COOL_ENV = "very cool"

# unset the given environmental variable. 
# NOTE: if an optional value is provided it will be used to set the environmental
# variable after unsetting
[unsetEnv]
COOL_ENV = "default"

